export AHN_PUNCHBLOCK_PLATFORM=asterisk
export AHN_PUNCHBLOCK_USERNAME="adhearsion"
export AHN_PUNCHBLOCK_PASSWORD="ClueCon"
export AHN_PUNCHBLOCK_HOST="192.168.251.128"
export AHN_PUNCHBLOCK_PORT=5038
#export AHN_PUNCHBLOCK_MEDIA_ENGINE=swift
